[general]
import = [
    "~/.config/alacritty/themes/github_dark.toml"
]

[font]
normal = { family = "JetBrainsMono Nerd Font Mono" }

[keyboard]
bindings = [
    { key = "Enter", mods = "Super", action = "ToggleFullscreen" }
    ]